blank_issues_enabled: false
contact_links:
  - name: ğŸ’¬ Github Discussion
    url: https://github.com/giovannilamarmora/lovelace-material-components/discussions/new?category=ideas
    about: Start a new discussion to share your ideas or ask questions.
  - name: ğŸ™ Home Assistant Community
    url: https://community.home-assistant.io/t/introducing-the-google-components/916428
    about: Visit the Home Assistant Community Forum to discuss with other users.
  - name: ğŸ“š Documentazione
    url: https://giovannilamarmora.gitbook.io/material-home-component
    about: Check out the documentation for guidance and information about the project.
